apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "chart.fullname" . }}-cron
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: test-env-job
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: IfNotPresent
            {{- include "chart.envFrom" . | nindent 12 }}
          restartPolicy: Never
