releases:
  - name: multiline-test-env
    namespace: multi-line
    chart: './chart'
    set:
      - name: 'name'
        value: |
          {{ if eq (env "STAGE") "production" }}
            Production
            Cluster
          {{ else if eq (env "STAGE") "integration" }}
            Integration
            cluster
          {{ else }}
            Staging
          {{ end }}
